version: "3.1"
services: 
  api-flix: 
    build: './'
    command: npm start
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: root
    env_file:
      - .env
    depends_on:
      - db-flix
    ports:
      - "4000:4000"
  db-flix: 
    build:
      context: './database'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"